export const images = {
  kedarkantha: [1, 2, 3, 4],
  banglore: [4],
  udaipur: [1, 2],
  yercaud: [1, 2],
  wayanad: [1, 2],
  pondicherry: [1, 2],
  coorg: [1, 2, 3],
  pollachi: [1],
  pichavaram: [1, 2],
  vizag: [1, 2],
  brahmatal: [2, 3],
  kanyakumari: [1],
  dandeli: [1, 2],
  'jog-falls': [1],
  'kundle-beach': [1],
  panjim: [1, 3],
  ponda: [1],
  varkala: [1, 2, 3, 4],
  rishikesh: [1]
};
